apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1-container
        image: demo0313tacr.azurecr.io/webapp1:0313a
        ports:
        - containerPort: 5000
        env:
        - name: ApplicationInsights__ConnectionString
          value: appInsigth-connection-strings-goes-here
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp1-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: webapp1
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 5000